#!/bin/bash
DIRECT_MAPPED="-s 3 -E 1 -b 3 -d 10"
SET_ASSOCIATIVE_1="-s 4 -E 2 -b 4 -d 10"
SET_ASSOCIATIVE_2="-s 2 -E 4 -b 3 -d 10"
FULLY_ASSOCIATIVE="-s 1 -E 4 -b 4 -d 10"
SE="./se -i "
TEST_1="testcases/week4/branch_not_taken"
TEST_2="testcases/week4/branch_taken"
TEST_3="testcases/week4/iter_sum"
TEST_4="testcases/week4/RAW"
TEST_5="testcases/week4/rec_sum"
TEST_6="testcases/week4/ret_hazard"
TEST_7="testcases/week4/shift"
TEST_8="testcases/week4/WAR"
OUTPUT=" grep 0x"

echo "Running test" $TEST_1
$SE $TEST_1 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_1 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_1 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_1 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_2
$SE $TEST_2 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_2 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_2 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_2 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_3
$SE $TEST_3 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_3 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_3 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_3 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_4
$SE $TEST_4 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_4 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_4 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_4 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_5
$SE $TEST_5 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_5 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_5 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_5 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_6
$SE $TEST_6 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_6 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_6 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_6 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_7
$SE $TEST_7 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_7 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_7 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_7 $FULLY_ASSOCIATIVE | $OUTPUT

echo "Running test" $TEST_8
$SE $TEST_8 $DIRECT_MAPPED | $OUTPUT
$SE $TEST_8 $SET_ASSOCIATIVE_1 | $OUTPUT
$SE $TEST_8 $SET_ASSOCIATIVE_2 | $OUTPUT
$SE $TEST_8 $FULLY_ASSOCIATIVE | $OUTPUT
